### ISSUE TITLE
[Correction] dans l'en tête de page: partie n'est pas remplie

### ISSUE THREAD

**Issue by rbleriot** [vincentchoqueuse/ENIB_latex_template#10]
![image](https://user-images.githubusercontent.com/120713707/208425925-8d9a180f-b990-4822-a22b-943ca3d8e664.png)

`\thepart` ne renvoi rien, mais je ne l'utilise peut-être pas correctement non plus

**Comment by vincentchoqueuse** [comment]
OK, j'ai enlevé la partie \thepart pour ne laisser que le chapitre.
