### ISSUE TITLE
[Exigence] 1 seule page pour le sommaire

### ISSUE THREAD

**Issue by rbleriot** [vincentchoqueuse/ENIB_latex_template#7]
`[...] Sommaire interactif dans le pdf (1 seule page)`

Apparement il faudrait limiter le sommaine à 1 page... je trouve ça un peu limitant tout de même mais bon, étant donné que le template est un `book` il y a forcément 2 pages à utiliser.

_source: https://wiki.enib.fr/re/doku.php?id=stages:rapport_

**Comment by vincentchoqueuse** [comment]
2 stratégies pour gérer ca :
* bien structurer son rapport (chapter / section ) pour que ca tienne dans un sommaire de 1 pages.
* régler dans le table of content la profondeur des items à afficher (afficher les sous-sections ?? les sous-sous sections ???)

Après, il ne faut pas trop se formaliser avec cette contrainte.
